mysqlServer: ''
mysqlPort: 3306
mysqlUsername: ''
mysqlPassword: ''
mysqlDatabase: ''
mysqlOption: '?allowPublicKeyRetrieval=true&useSSL=false'

discordToken: ''

NotificationChannel: '838583904456802334'