name: SurvivalPlugin
version: @version@
main: xyz.n7mn.dev.survivalplugin.SurvivalPlugin
api-version: 1.16
load: POSTWORLD
authors: [ 7mi_chan ]
description: SurvivalPlugin
commands:
  sigen:
    usage: '/sigen'
    description: ''
  main:
    usage: '/main'
    description: ''
  user:
    usage: '/user <mcid>'
    description: ''
    permission: '7miseikatu.op'
    permission-message: ''
  sethome:
    usage: '/sethome'
    description: ''
  home:
    usage: '/home'
    description: ''